CREATE TABLE IF NOT EXISTS relic_raid_state (
    state_key VARCHAR(64) NOT NULL PRIMARY KEY,
    payload LONGTEXT NOT NULL CHECK (JSON_VALID(payload)),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
        ON UPDATE CURRENT_TIMESTAMP(6)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
